In [1]:
import numpy as np

In [2]:
# Creating a matrix
matrix_A = np.array([[1, 2], [3, 4]])
print("Matrix A:\n", matrix_A)


Matrix A:
 [[1 2]
 [3 4]]


In [3]:
# Reshaping a matrix
reshaped_matrix = np.reshape(matrix_A, (4, 1))
print("Reshaped Matrix:\n", reshaped_matrix)


Reshaped Matrix:
 [[1]
 [2]
 [3]
 [4]]


In [4]:
# Changing values in a matrix
matrix_A[0, 0] = 5
print("Updated Matrix A:\n", matrix_A)

Updated Matrix A:
 [[5 2]
 [3 4]]


exercice cours 

In [5]:
import numpy as np

In [6]:
movie_ratings = np.array([
    [5, 1, 4],
    [4, 4, 2],
    [4, 3, 5],
    [1, 1, 5],
    [3, 2, 1]
])


In [7]:
average_responses = np.mean(movie_ratings, axis=0)
total_responses = np.sum(movie_ratings, axis=0)
max_responses = np.max(movie_ratings, axis=0)
min_responses = np.min(movie_ratings, axis=0)


In [8]:
 print("Average Responses:", average_responses)
print("Total Responses:", total_responses)
print("Maximum Responses:", max_responses)
print("Minimum Responses:", min_responses)

Average Responses: [3.4 2.2 3.4]
Total Responses: [17 11 17]
Maximum Responses: [5 4 5]
Minimum Responses: [1 1 1]


nouvel exo 


In [ ]:
matrix_B = np.array([[2, 3], [4, 5]])
matrix_C = np.array([[1, 1], [1, 1]])

In [9]:
import numpy as np


In [10]:

matrix_A = np.array([[1, 2, 3], 
                     [4, 5, 6], 
                     [7, 8, 9]])

matrix_B = np.array([[9, 8, 7], 
                     [6, 5, 4], 
                     [3, 2, 1]])


In [11]:
sum_matrix = np.add(matrix_A, matrix_B)

exercice


In [12]:
data = np.arange(1, 101)
