exercices 1


In [1]:
import numpy as np


arr = np.arange(10)

print(arr)


[0 1 2 3 4 5 6 7 8 9]


exercice 2

In [2]:
import numpy as np


arr = np.array([3.14, 2.17, 0, 1, 2])


arr_int = arr.astype(int)

print(arr_int)


[3 2 0 1 2]


exercice 3

In [3]:
import numpy as np


arr = np.arange(1, 10).reshape(3, 3)

print(arr)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


exercice 4

In [4]:
import numpy as np


arr = np.random.rand(4, 5)

print(arr)


[[0.08953123 0.9949009  0.22395785 0.46999743 0.78520383]
 [0.90322572 0.5514927  0.55455648 0.44733123 0.01067437]
 [0.4568656  0.52375223 0.1575936  0.67099985 0.39168585]
 [0.08685159 0.33156599 0.91566856 0.73105488 0.98935379]]


exercice 5

In [5]:
import numpy as np


arr = np.array([[21, 22, 23, 22, 22], 
                [20, 21, 22, 23, 24], 
                [21, 22, 23, 22, 22]])


second_row = arr[1]

print(second_row)


[20 21 22 23 24]


exercice 6

In [6]:
import numpy as np


arr = np.arange(10)


reversed_arr = arr[::-1]

print(reversed_arr)


[9 8 7 6 5 4 3 2 1 0]


exercice 7

In [7]:
import numpy as np


identity_matrix = np.eye(4)

print(identity_matrix)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
exercice 8

In [8]:
import numpy as np


arr = np.arange(10)

sum_arr = np.sum(arr)


avg_arr = np.mean(arr)

print(f"Sum: {sum_arr}, Average: {avg_arr}")


Sum: 45, Average: 4.5


exercice 9

In [9]:
import numpy as np

arr = np.arange(1, 21)

reshaped_arr = arr.reshape(4, 5)

print(reshaped_arr)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


exercice 10

In [10]:
import numpy as np


arr = np.arange(10)


odd_numbers = arr[arr % 2 != 0]

print(odd_numbers)


[1 3 5 7 9]
